###Testing endpoints usig VsCode REST Client extension
@api = http://localhost:3000

### / 
GET {{api}}


### /register
POST {{api}}/api/register
Content-Type: application/json

{
  "firstname": "Rick",
  "lastname": "Sanchez",
  "email": "rick.sanchez@rickandmorty.com",
  "password": "12345678",
  "password2": "12345678",
  "role": "coach"
  }

### /login
POST {{api}}/api/login
Content-Type: application/json

{
  "email": "rick.sanchez@rickandmorty.com",
  "password": "12345678"
}

###
POST  {{api}}/api/profile

###
GET {{api}}/api/logout

###
P {{api}}/api/user/61a50180a98d9c2bd858e111